export const aiConfigDefaults = {
    AI_MUST_ATTACK_RATIO: 1.25,
    AI_ATTACK_UPPER_BOUNDS: 0.8,
    AI_ATTACK_STICKINESS: 0.5,
    AI_EVALUATION_FREQUENCY: 0.5,
    AI_TACTICAL_AGGRESSION: 0.29,
    AI_RANDOM_AGGRESSION: 0.24,
} as const;
