export const gameplayConfigDefaults = {
    BASE_TICK_MS: 1450,
    MIN_TICK_MS: 100,
    ANIMATION_SPEED_MS: 1450,
    BIND_ANIMATION_TO_TICK: true,
    NUMBER_TRANSITION_MS: 250,
    LABEL_ANIM_MODE: 'rolling' as const,

    TRANSFER_RATE: 0.1,
    MIN_SHIPS_PER_TRANSFER: 0,
    MAX_SHIPS_PER_TRANSFER: 0,

    AGGRESSOR_ADVANTAGE: 0.7,
    GLOBAL_DAMAGE_MODIFIER: 8,
    LETHALITY: 0.25,
    FORCE_RATIO_EFFECT: 0,
    CONQUEST_THRESHOLD: 25,
    DAMAGED_SHIP_EFFECTIVENESS: 0.5,

    BASE_PRODUCTION: 0.6,

    REPAIR_RATE: 7,
    MIN_REPAIR: 1,
    REPAIR_COMBAT_PENALTY: 0.1,
    REPAIR_SUPPRESS_ATTACKER: 0.5,
    REPAIR_SUPPRESS_DEFENDER: 0.9,

    CONQUEST_TRANSFER_PERCENTAGE: 40,
    OVERWHELM_THRESHOLD: 0.1,
    ORDERS_PERSIST_AFTER_CONQUEST: true,
    RETAIN_ORDER_ON_CONQUEST: true,
    ALLOW_OPPOSING_ORDERS: false,
    CONQUEST_DAMAGED_CAPTURE_RATE: 1.0,
    CONQUEST_DAMAGED_DESTROY_RATE: 0,

    RETREAT_CAPTURE_RATE: 0.1,
    SCATTER_CAPTURE_RATE: 0.2,
    SCATTER_DESTROY_RATE: 0.5,
    RETREAT_DAMAGED_ACTIVATION_RATE: 0.1,
    STARTING_SHIPS: 70,

    HEX_RADIUS: 50,
    HEX_PADDING: 50,
    CONNECTION_MAX_DISTANCE: 150,
    MAPGEN_LANE_MARGIN_ENABLED: true,
    MAPGEN_LANE_MARGIN_PX: 75,
    MAPGEN_LANE_MODE: 'curved',
    MAPGEN_LANE_CURVE_VS_PRUNE_BIAS: 0.55,

    SHOW_HEX_GRID: false,
    STARS_PER_PLAYER: 7,

    _MAP_HEX_RADIUS: 0,
    _MAP_WIDTH: 0,
    _MAP_HEIGHT: 0,
    _MAP_PADDING_X: 0,
    _MAP_PADDING_Y: 0,

    MIN_LINKS_PER_STAR: 1,
    MAX_LINKS_PER_STAR: 6,
} as const;
