/**
 * build — mirror every .svelte file into `.sg-svelte/` as TSX so ast-grep can
 * scan Svelte markup with its real TypeScript engine.
 *
 * Run:  bun tools/svelte-tsx/build.ts [srcDir]      (default: src)
 *       bun run svelte:tsx
 *
 * The mirror keeps the source tree shape and the exact line numbering, so
 * `.sg-svelte/lib/components/ui/settings/Foo.svelte.tsx:123` is
 * `src/lib/components/ui/settings/Foo.svelte:123`. Use `sg-svelte.ts` to run
 * rules and get the original paths back automatically.
 *
 * The mirror is generated, gitignored, and safe to delete at any time.
 */

import { mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

import { svelteToTsx } from "./convert";

export const MIRROR_DIR = ".sg-svelte";

export function svelteFiles(root: string): string[] {
    const found: string[] = [];
    const walk = (dir: string) => {
        let entries: string[];
        try {
            entries = readdirSync(dir);
        } catch {
            return;
        }
        for (const entry of entries) {
            if (entry === "node_modules" || entry === ".svelte-kit" || entry === "_quarantine") continue;
            const full = path.join(dir, entry);
            if (statSync(full).isDirectory()) walk(full);
            else if (entry.endsWith(".svelte")) found.push(full);
        }
    };
    walk(root);
    return found;
}

/** Mirror path for a source file, relative to the client root. */
export function mirrorPathFor(clientRoot: string, sourceFile: string): string {
    const rel = path.relative(path.join(clientRoot, "src"), sourceFile);
    return path.join(clientRoot, MIRROR_DIR, `${rel}.tsx`);
}

/** Reverse of `mirrorPathFor`. */
export function sourcePathFor(clientRoot: string, mirrorFile: string): string {
    const rel = path.relative(path.join(clientRoot, MIRROR_DIR), mirrorFile);
    return path.join(clientRoot, "src", rel.replace(/\.tsx$/, ""));
}

export interface BuildResult {
    converted: number;
    failed: { file: string; error: string }[];
}

export function build(clientRoot: string, srcDir = "src"): BuildResult {
    const root = path.join(clientRoot, srcDir);
    const outRoot = path.join(clientRoot, MIRROR_DIR);
    rmSync(outRoot, { recursive: true, force: true });

    const failed: BuildResult["failed"] = [];
    let converted = 0;

    for (const file of svelteFiles(root)) {
        const source = readFileSync(file, "utf-8");
        let code: string;
        try {
            code = svelteToTsx(source, file).code;
        } catch (error) {
            failed.push({ file, error: String((error as Error).message ?? error) });
            continue;
        }
        const target = mirrorPathFor(clientRoot, file);
        mkdirSync(path.dirname(target), { recursive: true });
        writeFileSync(target, code, "utf-8");
        converted += 1;
    }

    // A generated tree that TypeScript picks up would flood `bun run check` with
    // nonsense errors. The mirror is for ast-grep only.
    writeFileSync(
        path.join(outRoot, "README.md"),
        "GENERATED by tools/svelte-tsx/build.ts — do not edit, do not commit, do not type-check.\n" +
            "Each file is a .svelte file re-emitted as TSX with identical line numbering,\n" +
            "so ast-grep can scan Svelte markup structurally. See tools/svelte-tsx/convert.ts.\n",
        "utf-8",
    );
    return { converted, failed };
}

if (import.meta.main) {
    const clientRoot = process.cwd();
    const result = build(clientRoot, process.argv[2] ?? "src");
    console.log(`svelte->tsx: ${result.converted} files -> ${MIRROR_DIR}/`);
    for (const failure of result.failed) {
        console.error(`  FAILED ${path.relative(clientRoot, failure.file)}: ${failure.error}`);
    }
    if (result.failed.length > 0) process.exit(1);
}
